### ISSUE TITLE
[Feature] JWT, Redis 기본 설정

### ISSUE THREAD

**Issue by hojeong2747** [PawWithU/ConnectDog-Server#11]
## 📑 작업 사항
JWT, Redis 기본 설정

## To-do
- [x] Member Entity 생성 (초안)
- [x] SecurityConfig 생성 및 기본 설정
- [x] 자체 회원가입 간단 구현
- [x] application-jwt.yml 추가
- [x] JwtService, JwtAuthenticationProcessingFilter 생성 및 기본 설정
- [x] RedisConfig, RedisUtil 생성 및 기본 설정
- [x] application.yml '.active' 추가
