### ISSUE TITLE
[Feature] 이동봉사 중개 봉사 완료 API 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#112]
## 📑 작업 사항
이동봉사 중개 봉사 완료 API 구현

## To-do
- [x] 신청 내역 가져오는 쿼리 Application 상태 조건 추가, 적용
- [x] 이동봉사 중개 봉사 완료 API 구현
- [x] 이동봉사 중개 봉사 완료 Controller 테스트 코드 추가
