### ISSUE TITLE
[Feature] JWT Handler 응답 및 API 권한 설정

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#133]
## 📑 작업 사항
JWT Handler 응답 및 API 권한 설정

## To-do
- [x] JWT Handler 응답 설정
- [x] 이동봉사 신청 API 권한 설정
- [x] 이동봉사 중개 API 권한 설정
