### ISSUE TITLE
[Feature] 기본 정보 조회 API 반환 추가 및 프로필 조회 API 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#139]
## 📑 작업 사항
마이페이지 기본 정보 조회 반환 추가 및 닉네임, 프로필 이미지 조회 API 구현

## To-do
- [ ] 마이페이지 기본 정보 조회 반환 추가
- [ ] 닉네임, 프로필 이미지 조회 API 구현
- [ ] Controller 테스트 코드 수정 및 추가
