### ISSUE TITLE
[Feature] 이동봉사자 후기 등록 검증 및 테스트 코드 수정

### ISSUE THREAD

**Issue by hojeong2747** [PawWithU/ConnectDog-Server#145]
## 📑 작업 사항
이동봉사자 후기 등록 검증 및 테스트 코드 수정 등

## To-do
- [x] 이동봉사자 후기 등록 검증
- [x] 북마크 등록/수정 uri 테스트 코드 수정
- [x] ErrorCode 수정
- [x] log 지우기
- [x] 뱃지 목록 조회 정렬 조건 추가
- [x] 더미데이터 수정 및 북마크 Time 추가
