### ISSUE TITLE
[Feature] 동시성 이슈 해결을 위한 DB Unique 조건 적용

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#155]
## 📑 작업 사항
동시성 이슈 해결을 위한 DB Unique 조건 적용

## To-do
- [x] Application 테이블 UniqueConstraint 설정
- [x] ApplicationService 공고 신청 로직 예외 처리
- [x] ApplicationService 공고 신청 테스트 코드 작성

## ETC
