### ISSUE TITLE
[Feature] 이동봉사자 봉사 관리 - 목록 조회 API 수정

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#157]
## 📑 작업 사항
이동봉사자 봉사 관리 - 목록 조회 API 수정

## To-do
- [x] 이동봉사자 승인 대기중 목록 조회 API 픽업 시간 추가
- [x] 이동봉사자 진행중 목록 조회 API 픽업 시간 추가
- [x] 이동봉사자 봉사 완료 목록 조회 API 근황 id 삭제 및 픽업 시간 추가
- [x] 이동봉사자 봉사 관리 - 목록 조회 테스트 코드 수정

**Comment by hojeong2747** [comment]
근황이 빠지고, 픽업시간까지 추가해 목록 조회하기 구현하셨네요! 
2차 개발 들어가고 코드리뷰 오랜만에 남기니 좀 설레네요..? ㅎㅎ
고생하셨습니다~!

아, 그리고 Dto 클래스에 ~completed 이런식으로 지은 거 직관적이고 너무 좋네요. 오랜만에 몇 달 전 작성한 남의 코드 보는데도 불구하고 기획서와 바로 매핑되어 아주 이해가 잘 돼요. 다들 클래스명 짓는 스타일도 다른데, 저는 코넥독 스타일이 좋아서 회사에서도 그렇게 쓰고 있답니다👍
