### ISSUE TITLE
[Feature] 공고 강아지 성별, 몸무게 제거 및 API 수정

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#159]
## 📑 작업 사항
공고 강아지 성별, 몸무게 제거 및 API 수정

## To-do
- [x] 공고 강아지 성별, 몸무게 제거
- [x] 공고 등록 API - 강아지 성별, 몸무게 제거
- [x] 이동봉사자 공고 상세 보기 API - 강아지 성별, 몸무게 제거
- [x] 이동봉사 중개 공고 상세 보기 API - 강아지 성별, 몸무게 제거
- [x] 공고 상세 보기 테스트 코드 수정
- [x] import.sql dog 관련 수정

## ETC
