### ISSUE TITLE
[Feature] 이동봉사자 봉사 관리 - 목록 조회 API 추가 수정

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#161]
## 📑 작업 사항
이동봉사자 봉사 관리 - 목록 조회 API 추가 수정

## To-do
- [x] 이동봉사자 승인 대기중 목록 조회 API 반환값 수정
- [x] 이동봉사자 진행중 목록 조회 API 반환값 수정
- [x] 이동봉사자 봉사 완료 목록 조회 API 반환값 수정
- [x] 이동봉사자 봉사 관리 - 목록 조회 테스트 코드 수정
