### ISSUE TITLE
[Feature] 이동봉사 모집자 봉사 관리 - 목록 조회 API 수정

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#163]
## 📑 작업 사항
이동봉사 모집자 봉사 관리 - 목록 조회 API 수정

## To-do
- [x] 이동봉사 모집자 승인 대기중 목록 조회 API 반환값 수정
- [x] 이동봉사 모집자 진행중 목록 조회 API 반환값 수정
- [x] 이동봉사 모집자 봉사 완료 목록 조회 API 반환값 수정
- [x] 이동봉사 모집자 봉사 관리 - 목록 조회 테스트 코드 수정
- [x] DogSize enum 값 소형견 -> 소형 형식으로 수정
- [x] 이동봉사 모집자 모집중, 모집 마감 목록 조회 API 반환값 수정
