### ISSUE TITLE
[Feature] 이동봉사자, 모집자 자체 회원가입 API 수정

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#165]
## 📑 작업 사항
이동봉사자, 모집자 자체 회원가입 API 수정

## To-do
- [x] 이동봉사자 자체 회원가입 API 수정
- [x] 모집자 자체 회원가입 API 수정
- [x] 모집자 이름, 전화번호 필드 추가
- [x] 이동봉사자, 모집자 자체 회원가입 테스트 코드 수정

## ETC
