### ISSUE TITLE
[Feature] 이동봉사자, 모집자 휴대폰 번호 중복 검사 API 구현 

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#167]
## 📑 작업 사항
이동봉사자, 모집자 휴대폰 번호 중복 검사 API 구현 

## To-do
- [x] 이동봉사자 휴대폰 번호 중복 검사 API 구현 
- [x] 모집자 휴대폰 번호 중복 검사 API 구현 
- [x] 이동봉사자, 모집자 휴대폰 번호 중복 검사 Controller 테스트 코드 추가
