### ISSUE TITLE
[Feature] 이동봉사자, 모집자 - 모집자 프로필 공고 조회 API 수정

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#171]
## 📑 작업 사항
이동봉사자, 모집자 - 모집자 프로필 공고 조회 API 수정

## To-do
- [x] 이동봉사자, 모집자 - 모집자 프로필 공고 조회 API 반환값 수정
- [x] 이동봉사자, 모집자 - 모집자 프로필 공고 조회 API 정렬 기준 추가
- [x] 이동봉사자, 모집자 - 모집자 프로필 공고 조회 테스트 코드 수정

## ETC
