### ISSUE TITLE
[Feature] 이동봉사 신청 관련 API 수정

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#177]
## 📑 작업 사항
이동봉사 신청 관련 API 수정

## To-do
- [x] 이동봉사 신청 - 운송 수단 삭제 및 "반려" 상태 추가
- [x] 이동봉사 신청 API 수정
- [x] 봉사자, 모집자 이동봉사 신청 내역 단건 조회 dto 수정
- [x] 이동봉사 신청 반려 시 신청 상태 "반려"로 변경
- [x] 이동봉사 신청 DB 제약 조건 해제 및 API 수정
- [x] import.sql 수정
- [x] 이동봉사 신청 관련 테스트 코드 수정

## ETC
