### ISSUE TITLE
[Feature] 홈 화면 공고 조회, 공고 필터 검색 API 반환값 수정

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#182]
## 📑 작업 사항
홈 화면 공고 조회, 공고 필터 검색 API 반환값 수정

## To-do
- [x] 홈 화면 공고 조회 API 반환값 수정
- [x] 공고 필터 검색 API 반환값 수정
- [x] 홈 화면 공고 조회, 공고 필터 검색 Controller 테스트 코드 수정
