### ISSUE TITLE
[Feature] 봉사자 공고 관련 API 수정

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#185]
## 📑 작업 사항
봉사자 공고 관련 API 수정

## To-do
- [x] 봉사자 홈 화면 공고 조회 - 6개 조회로 변경
- [x] 공고 필터 검색 - default: 최근 등록순으로 변경 (모집자 프로필 - default: 최근 등록순 -> 마감 임박순 워딩 변경)
- [x] 공고 신청 시 Validation 추가 및 워딩 변경

## ETC
