### ISSUE TITLE
[Feature] 봉사자, 모집자 알림 목록 조회 API 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#195]
## 📑 작업 사항
봉사자, 모집자 알림 목록 조회 API 구현

## To-do
- [x] 봉사자, 모집자 알림 목록 조회 API 구현
- [x] 봉사자, 모집자 알림 목록 조회 Controller 테스트 코드 추가
- [x] @ Enumerated(EnumType.STRING) 추가

## ETC
