### ISSUE TITLE
[Feature] 이동봉사자, 이동봉사 중개 자체 회원가입 API 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#21]
## 📑 작업 사항
이동봉사자, 이동봉사 중개 자체 회원가입 API 구현

## To-do
- [x] 이동봉사자 자체 회원가입 API 구현
- [x] AWS S3 설정
- [x] 이동봉사 중개 자체 회원가입 API 구현
- [x] Controller 테스트 코드 추가
