### ISSUE TITLE
[Feature] 발생되는 이슈 수정

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#220]
## 📑 작업 사항
발생되는 이슈 수정

## To-do
- [x] 모집자 가입시 권한 수정 및 링크 선택 사항으로 변경
- [x] 알림 설정 관련 uri 수정
- [x] import.sql 공고 시간 변경
- [x] fcm token 저장 api 수정
