### ISSUE TITLE
[Feature] 모집자, 봉사자 내 정보 관리 및 모집자명 중복 확인 API 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#222]
## 📑 작업 사항
모집자, 봉사자 내 정보 관리 및 모집자명 중복 확인 API 구현

## To-do
- [x] 모집자 - 내 정보 관리 API 구현
- [x] 봉사자 - 내 정보 관리 API 구현
- [x] 모집자명 중복 확인 API 구현
- [x] 내 정보 관리 및 모집자명 중복 확인 테스트 코드 추가
