### ISSUE TITLE
[Feature] 공고 끌어올리기 API 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#242]
## 📑 작업 사항
공고 끌어올리기 API 구현

## To-do
- [x] Post 끌어올리기 Column 추가 및 적용
- [x] 공고 끌어올리기 API 구현
- [x] Controller 테스트 코드 추가
