### ISSUE TITLE
[Feature] 공고 연장하기 API 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#244]
## 📑 작업 사항
공고 연장하기 API 구현

## To-do
- [x] 공고 연장하기 API 구현
- [x] Controller 테스트 코드 추가
- [x] 공고 목록 조회 정렬 기준 변경

## ETC
