### ISSUE TITLE
[Feature] 이동봉사자, 이동봉사 중개 Entity 필드 추가

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#27]
## 📑 작업 사항
이동봉사자, 이동봉사 중개 Entity 필드 추가

## To-do
- [x] 이동봉사자 Entity 필드 추가 -> 이동봉사자 자체 회원가입 API 수정
- [x] 이동봉사 중개 Entity 필드 추가 -> 이동봉사 중개 자체 회원가입 API 수정
- [x] 이동봉사 중개 자체 회원가입 시 프로필 사진 업로드 로직 추가
- [x] Controller 테스트 코드 수정
