### ISSUE TITLE
[Deploy] CI/CD 구축

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#3]
## 📑 작업 사항
CI/CD 구축

## To-do
- [x] appspec.yml 파일 생성
- [x] deploy.sh 파일 생성
- [x] Dockerfile, docker-compose.yml 파일 생성
- [x] deploy.yml 파일 생성

**Comment by hojeong2747** [comment]
이 많은 걸 전부 쓰기로 했는데 다 잘 다루다니.. 역시! 
우리 서버 자랑스럽게 말 할 수 있겠는데요?
