### ISSUE TITLE
[Feature] 이동봉사 중개 공고 등록 API 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#35]
## 📑 작업 사항
이동봉사 중개 공고 등록 API 구현

## To-do
- [x] Post의 mainImage 필드 -> PostImage를 외래 키로 받도록 변경 (1:1 연관 관계)
- [x] Enum -> @JsonCreater 적용
- [x] 이동봉사 중개 공고 등록 API 구현
- [x] 이동봉사 중개 공고 등록 Controller 테스트 코드 추가
