### ISSUE TITLE
[Deploy] Blue, Green 배포 시 Health Check 기능 추가

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#5]
## 📑 작업 사항
Blue, Green 배포 시 Health Check 기능 추가

## To-do
- [x] 새로운 컨테이너의 Health Check 기능 추가
- [x] 해당 컨테이너가 Health Check에 실패한다면 Slack에 배포 실패 알림 보내는 기능 추가
- [x] 해당 컨테이너가 Health Check에 성공한다면 이전 컨테이너를 내리는 기능 추가
