### ISSUE TITLE
[Feature] 이동봉사자 봉사 관리 - 승인 대기중, 진행중 목록 조회 API 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#56]
## 📑 작업 사항
이동봉사자 봉사 관리 - 승인 대기중, 진행중 목록 조회 API 구현

## To-do
- [x] 이동봉사자 승인 대기중 목록 조회 API 구현
- [x] 이동봉사자 승인 대기중 목록 조회 Controller 테스트 코드 추가
- [x] 이동봉사자 진행중 목록 조회 API 구현
- [x] 이동봉사자 진행중 목록 조회 Controller 테스트 코드 추가
- [x] 더미 데이터 추가
