### ISSUE TITLE
[Feature] 이동봉사자, 이동봉사 중개 봉사 완료 목록 조회 API 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#76]
## 📑 작업 사항
이동봉사자, 이동봉사 중개 봉사 완료 목록 조회 API 구현

## To-do
- [x] 이동봉사자 봉사 완료 목록 조회 API 구현
- [x] 이동봉사자 봉사 완료 목록 조회 Controller 테스트 코드 추가
- [x] 이동봉사 중개 봉사 완료 목록 조회 API 구현
- [x] 이동봉사 중개 봉사 완료 목록 조회 Controller 테스트 코드 추가
