### ISSUE TITLE
[Feature] 전역적 예외 처리 설정

### ISSUE THREAD

**Issue by hojeong2747** [PawWithU/ConnectDog-Server#8]
## 📑 작업 사항
전역적 예외 처리 설정

## To-do
- [x] 전역적인 예외 처리를 위한 핸들러 클래스 추가
- [x] ErrorCode 클래스 추가
- [x] Custom 예외 클래스 추가
