### ISSUE TITLE
[Feature] 이동봉사 중개 공고 상세 조회 API 구현

### ISSUE THREAD

**Issue by kyeong-hyeok** [PawWithU/ConnectDog-Server#89]
## 📑 작업 사항
이동봉사 중개 공고 상세 조회 API 구현

## To-do
- [x] 이동봉사 중개 공고 상세 조회 API 구현
- [x] 이동봉사 중개 공고 상세 조회 Controller 테스트 코드 추가
- [x] 이동봉사자 공고 상세 조회 시 공고 존재 여부 검증 로직 추가

## ETC
